### ISSUE TITLE
issue documenting xarray accessor

### ISSUE THREAD

**Issue by jucordero** [xarray-contrib/sphinx-autosummary-accessors#107]
I'm trying to write documentation for an xarray accessor class 

```python
@xr.register_dataset_accessor("fbs")
class FoodBalanceSheet:

    def _validate(obj):
        ...
    def add_items(self, items, copy_from=None):
        ...
```

But haven't been able to correctly interpret the examples to adapt to my case.

I have added the extension to conf.py
``` python
import sphinx_autosummary_accessors
...
extensions = [ ...
"sphinx_autosummary_accessors",
... ]
templates_path = ['_templates', sphinx_autosummary_accessors.templates_path]
```

I'm not sure if I'm doing the directives right
In index.rst I have:

```rst
.. currentmodule:: xarray
.. autosummary::
   :toctree: generated/
   :template: autosummary/accessor_method.rst

   Dataset.fbs.add_items
```

But I get
`Handler <function process_generate_options at 0x7f681000e1f0> for event 'builder-inited' threw an exception (exception: no module named xarray.Dataset.fbs)
`

Tried different things (adding my package to path, adding the `currentmodule` directive) but don't really know what I'm doing.
Any help would be greatly appreciated!

**Comment by keewis** [comment]
apologies for the delay here. I was not sure how we solve this, but it appears you *have* to import your module (or at least the part of the module that defines the accessor) in your `conf.py`. After that the accessor is registered, so building the module should work.
