### ISSUE TITLE
Documenting accessor instance class (subaccessor) methods.

### ISSUE THREAD

**Issue by juseg** [xarray-contrib/sphinx-autosummary-accessors#21]
Hello, this is potentially a more general question about designing xarray extensions.

### Summary

I am working on a library implementing accessor `hyoga` , which during `__init__()` plugs an instance object `plot`, eventually accessible as `xarray.Dataset().hyoga.plot`. Using sphinx-autosummary-accessors nicely builds autodocs for `xarray.Dataset.hyoga.methods()` but fails on the `xarray.Dataset.hyoga.plot.methods()`.

### Details

For instance:

``` rst
.. currentmodule:: xarray
.. autosummary::
   :toctree: generated/
   :template: autosummary/accessor_method.rst

   Dataset.hyoga.plot.bedrock_altitude
```

Yields the warnings:

```
[autosummary] generating autosummary for: api.rst, index.rst, opening.rst, plotting.rst, whatsnew.rst
WARNING: [autosummary] failed to import 'xarray.Dataset.hyoga.plot.bedrock_altitude': no module named 
[...]
reading sources... [100%] whatsnew                                                                                                                                                             
/home/julien/git/code/hyoga/doc/api.rst.rst:51: WARNING: autosummary: failed to import Dataset.hyoga.plot.bedrock_altitude
```

### Partial fix

The first warning disappears and sphinx generates a method signature in api.html, if I make the plotting class an attribute of the main accessor class, overriden by the plotting object in `__init__`:

``` python
@xr.register_dataset_accessor('hyoga')
class HyogaDataset:
    plot = hyoga.plot.HyogaPlotMethods

    def __init__(self, dataset):
        self.plot = hyoga.plot.HyogaPlotMethods(dataset)
```

The generated rst file looks like this:

``` rst
xarray.Dataset.hyoga.plot.bedrock_altitude                                                                                                                                                 
==========================================

.. currentmodule:: xarray

.. autoaccessormethod:: Dataset.hyoga.plot.bedrock_altitude
```

But this fails to be parsed and the second warning becomes:

```
WARNING: autodoc: failed to import accessormethod 'hyoga.plot.bedrock_altitude' from module 'Dataset'; the following exception was raised:
No module named 'Dataset'
```

### Question

I am wondering if sphinx-autosummary-accessors can be extended to include such "subaccessors", or even if I should perhaps consider an alternative design for my library.

Current api without sphinx-autosummary-accessors: https://hyoga.readthedocs.io/en/latest/api.html. Thank you!

**Comment by keewis** [comment]
my guess is that you will have to use something like `xarray.core.utils.UncachedAccessor` or `xarray.core.extensions._CachedAccessor` to attach your plot methods. Your accessor would then look like this:

```python
@xr.register_dataset_accessor("hyoga")
class DatasetAccessor:
    plot = UncachedAccessor(hyuga.plot.HyogaPlotMethods)
```
The reason for this is that `sphinx` looks at the classes, not instances (and we want to use a descriptor because then we don't have to create a plot object in `__init__`.

That said I didn't think of nested accessors when I wrote this library so I wouldn't be too surprised if the custom documenters break.

**Comment by keewis** [comment]
the current code in `AccessorLevelDocumenter` assumes either `module.class.accessor.func` or `class.accessor.func`, which means that with `Dataset.hyoga.plot.func` `Dataset` is assumed to be the module.

A potential fix would be to try importing the extracted module then accessing the specified attributes (see #23).

**Comment by keewis** [comment]
Re library design: nested accessors don't seem to be too uncommon (`cf-xarray` also uses them) so I don't think you have to change your library. However, instead of setting it as a instance attribute you should use a descriptor (`UncachedAccessor`, probably).

**Comment by juseg** [comment]
Thank you very much for all the feedback and code changes! I understand the need for `UncachedAcessor` now, and nested accessor autodocs build smoothly on the subaccessor branch (b407985ba763e856c6fd2cf85d744e047f06630b).

**Comment by keewis** [comment]
great. I'll issue a release soon.

**Comment by keewis** [comment]
the new version is on PyPI and should soon also be available on conda-forge.
