### ISSUE TITLE
organisational issues

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/sphinx-autosummary-accessors#3]
With #2, the internal documentation works and it is time to check if that's also the case for `pandas` and `xarray`. There are also a few open issues:
1. I'd like to move the main repository out of my own personal "organization", but where should this live?
2. ~naming: `accessors` seems to be available in PyPI so we could go with that, but `sphinx-ext-accessors` or something similar would also be possible.~ it is now named `sphinx-autosummary-accessors`
3. ~location of the templates: right now, they are in the main templates directory, so they are used with `:template: accessor_method.rst`, but `pandas` and `xarray` seem to use `autosummary/accessor_method.rst` instead. We probably should copy that~ done
4. license: I chose MIT, but `pandas` is under the BSD 3-clause. I don't really care about the license, but I think there has to have been at least some discussion about that. Also, since this is mostly code from `pandas` it would probably be good to ask them.

cc @benbovy, @shoyer, @TomAugspurger

**Comment by benbovy** [comment]
1. I think it could fit in [xarray-contrib](https://github.com/xarray-contrib).

2. I like the `sphinx-` prefix in the name, maybe `sphinx-autosummary-accessors` or `sphinx-autodoc-accessors` would be even more explicit?

**Comment by keewis** [comment]
> I think it could fit in xarray-contrib.

I've been thinking about that, but if we want to have `pandas` also use it this might be a bit strange (not sure if that's really an issue, though)

> maybe `sphinx-autosummary-accessors` or `sphinx-autodoc-accessors` would be even more explicit

I like those, although I'd rule out the `autodoc` name since we don't use it directly

**Comment by keewis** [comment]
okay, with this we resolved all of my initial questions except the licensing. And since we were able to close / resolve #7, this means that we can a release this.

I'll raise this on the pandas issue tracker (and also invite them to use this :grin:).

**Comment by keewis** [comment]
closed by #13, I guess?
